name: Build Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Run on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      # Build in a specific directory
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      # Build the target
      run: cmake --build ${{github.workspace}}/build --config Release
    
    - name: Run Sanity Check
      # Run the executable
      run: ${{github.workspace}}/build/evtol_sim
